import '../models/cell_state.dart';
import 'adjacency.dart';
import 'game_rules_config.dart';

/// Axis 1: Infection Resolution Mode — controls HOW ownership changes resolve.
enum InfectionResolutionMode {
  /// Ownership change resolves via a neutral (gray) intermediate state.
  /// Opponent neighbors → neutral; neutral neighbors → attacker.
  neutralIntermediary,

  /// Ownership transfers directly. Opponent neighbors → attacker directly.
  /// No gray states are ever generated in this mode.
  directTransfer,
}

/// Centralized infection resolution provider. This is the single source of truth
/// for applying ownership transitions to a set of affected neighbors returned by
/// the adjacency provider. The default mode preserves current gameplay behavior.
class InfectionResolution {
  /// Apply ownership transitions to the provided [neighbors] around the last
  /// placement at (r,c). The [board] must be a mutable clone of the source.
  /// Common exclusions: bombs/walls are ignored; empty cells are ignored; the
  /// attacker's own color is not changed.
  static void applyOwnershipTransitions(
    List<List<CellState>> board,
    int r,
    int c,
    CellState attacker,
    Iterable<(int, int)> neighbors,
    InfectionResolutionMode resolutionMode,
  ) {
    for (final (nr, nc) in neighbors) {
      final s = board[nr][nc];
      // Skip special blockers entirely
      if (s == CellState.bomb || s == CellState.wall) continue;
      // Skip empty and own color
      if (s == CellState.empty || s == attacker) continue;

      switch (resolutionMode) {
        case InfectionResolutionMode.neutralIntermediary:
          if (s == CellState.neutral) {
            // Claim neutral cells adjacent to placement
            board[nr][nc] = attacker;
          } else {
            // Any opponent color becomes neutral
            board[nr][nc] = CellState.neutral;
          }
          break;
        case InfectionResolutionMode.directTransfer:
          if (s == CellState.neutral) {
            // In direct transfer, gray is not part of resolution semantics;
            // do not alter existing gray tiles here (they should not be
            // generated by this mode, and gray-drop is disabled elsewhere).
            continue;
          } else {
            // Any opponent color converts directly to attacker
            board[nr][nc] = attacker;
          }
          break;
      }
    }
  }

  /// Convenience overload that uses the current GameRulesConfig and adjacency.
  static void applyUsingDefaults(
    List<List<CellState>> board,
    int r,
    int c,
    CellState attacker,
  ) {
    final neighbors = Adjacency.neighborsOf(r, c);
    final mode = GameRulesConfig.current.resolutionMode;
    applyOwnershipTransitions(board, r, c, attacker, neighbors, mode);
  }
}
